### ISSUE TITLE
no such method error

### ISSUE THREAD

**Issue by kematusik** [paulscherrerinstitute/ch.psi.imagej.hdf5#6]
I am using ImageJ version 1.53f and Java 1.8.0_112 (64-bit) with Ubuntu 16.04 LTS. When I copy the HDF5_Viewer-0.13.0.jar file into ImageJ/plugins folder, restart ImageJ, and try to load an HDF file, I get the following error:

ImageJ 1.53f; Java 1.8.0_112 [64-bit]; Linux 4.15.0-122-generic; 95MB of 100000MB (<1%)
java.lang.NoSuchMethodError: org.slf4j.Logger.trace(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
	at hdf.object.FileFormat.<init>(FileFormat.java:315)
	at hdf.object.h5.H5File.<init>(H5File.java:174)
	at hdf.object.h5.H5File.<init>(H5File.java:127)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at hdf.object.FileFormat.<clinit>(FileFormat.java:228)
	at ch.psi.imagej.hdf5.HDF5Reader.open(HDF5Reader.java:82)
	at ch.psi.imagej.hdf5.HDF5Reader.open(HDF5Reader.java:51)
	at ch.psi.imagej.hdf5.HDF5Reader.run(HDF5Reader.java:36)
	at ij.IJ.runUserPlugIn(IJ.java:241)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:745)

These files work with HDF5_Vibez, so I know it isn't a corrupt file issue. I also removed the HDF5_Vibez.jar file from the plugins folder.

**Comment by simongregorebner** [comment]
Hmmm.... I guess the latest jar was build with Java 11 and the Readme was not updated by me. I need to check.
Maybe, in the meantime, could you try to run ImageJ with a java >=11 ?

**Comment by kasia21** [comment]
It seems to work with ImageJ bundled with Java 1.8.0_172; thanks!
